"""
Generate Response Options Tool - Tool for ConvoBridge Response Agent
This tool generates response options based on dimension, question, and sentence difficulty level.
"""

from typing import List
from pathlib import Path
from dotenv import load_dotenv
import json
import os
import re

# Import OpenAI for direct LLM calls
try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

# Load .env file from the backend directory
backend_dir = Path(__file__).parent.parent
env_path = backend_dir / '.env'
load_dotenv(dotenv_path=env_path)


def generate_response_options(
    question: str,
    dimension: str,
    sentence_difficulty_level: int = 1
) -> List[str]:
    """
    Generate 2 response options based on the question, dimension, and sentence difficulty level.
    
    The difficulty levels are:
    - Level 1: Simple and direct responses
    - Level 2: Medium complexity with some detail
    - Level 3: More elaborate with reasoning (2-3 sentences with complex high school vocabulary)
    
    Args:
        question: The question generated by the conversation agent
        dimension: The conversation dimension (e.g., "basic preferences", "social context", "emotional")
        sentence_difficulty_level: The current sentence difficulty level (1, 2, or 3). Defaults to 1.
    
    Returns:
        A list of exactly 2 response option strings that are appropriate for the question,
        dimension, and difficulty level.
        
    Example:
        >>> options = generate_response_options(
        ...     question="What type of video games do you enjoy playing?",
        ...     dimension="basic preferences",
        ...     sentence_difficulty_level=1
        ... )
        >>> len(options)
        2
        >>> isinstance(options[0], str)
        True
    """
    # Validate difficulty level
    if sentence_difficulty_level < 1 or sentence_difficulty_level > 3:
        sentence_difficulty_level = 1  # Default to Level 1 if invalid
    
    # Build difficulty description
    difficulty_descriptions = {
        1: "simple and direct",
        2: "medium complexity with some detail",
        3: "more elaborate with reasoning, 2-3 sentences with complex high school vocabulary"
    }
    
    difficulty_desc = difficulty_descriptions.get(sentence_difficulty_level, "simple and direct")
    
    # Build dimension-specific guidance
    dimension_guidance = {
        "basic preferences": "focus on likes, dislikes, favorites, and simple choices",
        "depth/specificity": "provide more detailed and specific information",
        "social context": "mention friends, family, or social situations",
        "emotional": "express feelings, excitement, frustration, or reactions",
        "temporal/frequency": "include time-based information, frequency, or past experiences",
        "comparative": "compare two things or express preferences",
        "reflective/why": "explain reasons, motivations, or 'why' behind choices",
        "descriptive/detail": "include sensory details, appearance, or setting descriptions",
        "challenge/growth": "discuss learning curves, difficulties, or improvements"
    }
    
    dimension_guidance_text = dimension_guidance.get(
        dimension.lower(),
        "provide an appropriate response"
    )
    
    # Create a prompt for generating responses
    prompt = f"""Generate exactly 2 response options for this question: "{question}"

Requirements:
- Dimension: {dimension} - {dimension_guidance_text}
- Difficulty Level {sentence_difficulty_level}: {difficulty_desc}
- Make responses non-deterministic and adapt to the specific question
- Keep responses natural and conversational
- Return ONLY a JSON array with exactly 2 response strings

Example for Level 1: ["I really enjoy playing action games.", "I prefer puzzle games more."]
Example for Level 2: ["I really enjoy playing action games because they're fast-paced and exciting.", "I prefer puzzle games more since they challenge my problem-solving skills."]
Example for Level 3: ["I find action games particularly engaging because they require quick reflexes and strategic thinking, which keeps me constantly focused and entertained.", "Puzzle games appeal to me more as they provide intellectual stimulation and allow me to work through complex challenges at my own pace."]

Return ONLY the raw JSON array, nothing else."""
    
    # Use OpenAI directly to generate the actual options
    api_key = os.getenv('OPENAI_API_KEY')
    if OpenAI and api_key:
        try:
            client = OpenAI(api_key=api_key)
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {
                        "role": "system",
                        "content": "You are a response option generator for autistic youth conversation practice. Generate exactly 2 response options as a JSON array."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.8,  # Higher temperature for non-deterministic responses
                response_format={"type": "json_object"} if False else None  # Not using JSON mode to get array directly
            )
            
            response_content = response.choices[0].message.content.strip()
            
            # Parse the JSON response
            # Remove markdown code blocks if present
            response_content = response_content.replace('```json', '').replace('```', '').strip()
            
            # Try to find JSON array in the response
            json_match = re.search(r'\[.*?\]', response_content, re.DOTALL)
            if json_match:
                response_content = json_match.group(0)
            
            # Parse the JSON
            options = json.loads(response_content)
            
            # Ensure we have exactly 2 options
            if isinstance(options, list) and len(options) >= 2:
                return options[:2]  # Return first 2 options
            elif isinstance(options, list) and len(options) == 1:
                # If only one option, duplicate it (fallback)
                return [options[0], options[0]]
            else:
                # Fallback to default options
                return [
                    "I like that topic.",
                    "I'm not sure about that."
                ]
        except Exception as e:
            print(f"Error generating response options with OpenAI: {e}")
            # Fallback to default options
            return [
                "I like that topic.",
                "I'm not sure about that."
            ]
    else:
        # Fallback if OpenAI is not available
        return [
            "I like that topic.",
            "I'm not sure about that."
        ]


if __name__ == "__main__":
    # Simple test
    print("Generate Response Options Tool - Ready!\n")
    
    # Test with Level 1
    prompt1 = generate_response_options(
        question="What type of video games do you enjoy playing?",
        dimension="basic preferences",
        sentence_difficulty_level=1
    )
    print("Level 1 Prompt:")
    print(prompt1)
    print()
    
    # Test with Level 2
    prompt2 = generate_response_options(
        question="What type of video games do you enjoy playing?",
        dimension="basic preferences",
        sentence_difficulty_level=2
    )
    print("Level 2 Prompt:")
    print(prompt2)
    print()
    
    # Test with Level 3
    prompt3 = generate_response_options(
        question="What type of video games do you enjoy playing?",
        dimension="basic preferences",
        sentence_difficulty_level=3
    )
    print("Level 3 Prompt:")
    print(prompt3)
